# Generated by Django 4.2.7 on 2025-09-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_texts', models.IntegerField(default=0, help_text='Total de textos aprovados', verbose_name='Textos Aprovados')),
                ('denied_texts', models.IntegerField(default=0, help_text='Total de textos negados', verbose_name='Textos Negados')),
                ('generated_texts', models.IntegerField(default=0, help_text='Total de textos gerados', verbose_name='Textos Gerados')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Texto de entrada fornecido pelo usuário', verbose_name='Descrição')),
                ('text_content', models.TextField(help_text='Conteúdo gerado pelo modelo de linguagem', verbose_name='Conteúdo do Texto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('is_approved', models.BooleanField(default=False, help_text='Status de aprovação do texto', verbose_name='Aprovado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Texto',
                'verbose_name_plural': 'Textos',
                'ordering': ['-created_at'],
            },
        ),
    ]
